version: '3.3'
services:
  jwt_db:
    image: 'postgres:12.3-alpine'
    container_name: jwt_db
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGERS_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jwt-tutorial
  jwt_server:
    image: node:12.18.2
    container_name: jwt_server
    volumes:
      - ./server:/root/server
      - /root/server/node_modules/
    working_dir: /root/server
    ports:
      - '8080:8080'
    command: bash -c 'yarn && yarn start'
  jwt_client:
    image: node:12.18.2
    container_name: jwt_client
    volumes:
      - ./client:/root/client
      - /root/client/node_modules/
    working_dir: /root/client
    ports:
      - '3000:3000'
    command: bash -c 'yarn && yarn start'
    stdin_open: true
